development: &default
  min_messages: warning
  pool: <%= [ENV.fetch("MAX_THREADS", 5).to_i, ENV.fetch("DB_POOL", 5).to_i].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

test:
  <<: *default

production: &deploy
  <<: *default
